### ISSUE TITLE
SPIKE: Decide on best method for cloud infrastructure requisition/setup (copied from original repo)

### ISSUE THREAD

**Issue by Ricool06** [Ricool06/breathe#1]
This spike is to decide the method of requisitioning infrastructure. In effect, the project needs an infrastructure as code tool, whether that be Terraform, Ansible, or even just AWS Elastic Beanstalk JSON files as used in cop-watch, the following requirements must be met by the proposed tool:

* Free to use
* Supports deployment from monorepo
* Supports AWS (all needed from ECS, Lmbda, DynamoDB, S3)
* Easy to learn/use

## Tasks
- [x] Create list of proposed IAC tools
- [x] Create comparison matrix including above criteria for each
- [x] Try out each system and fill in matrix
- [x] Document chosen system on Github wiki/README of project

**Comment by Ricool06** [comment]
Done! Terraform it is.
Choice and example is documented on the wiki: https://github.com/Plymouth-University/prco304-final-year-project-Ricool06/wiki/SPIKE:-Decide-on-best-method-for-cloud-infrastructure-requisition-setup-%234

Lessons learned are also documented there. Terraform isn't as scary as it first seems. Is perhaps more suitable than Ansible for most modern apps and services. Ansible would be more appropriate for setting up on-prem infrastructure.
