### ISSUE TITLE
Display empty map on main page

### ISSUE THREAD

**Issue by Ricool06** [Ricool06/breathe#15]
As a: user
I want: to be able to explore a map
So that: I can interactively explore and discover locations of interest

#### Tasks
- [x] Quickly (not worth a spike) decide on a geographic map framework to use (Leaflet or otherwise)
- [x] Create map component
- [x] Create map container
- [x] Set up routing to display map by default

#### Acceptance:
- [x] Deployed web app includes empty map that is pannable & zoomable

**Comment by Ricool06** [comment]
Choice came down to OpenLayers vs Leaflet. Leaflet is simpler, seems to have more plugins, both have active communities, but Leaflet has smaller package size and I know it does what I want.

**Comment by Ricool06** [comment]
Terraform needed to perform some hash checks between current and previous zip, but other than that, smooth sailing. Map is now available, delivered serverlessly.
