### ISSUE TITLE
Display current air quality data on the map

### ISSUE THREAD

**Issue by Ricool06** [Ricool06/breathe#16]
As a: user
I want: to be able to view current air quality data
So that: I can decide what action to take in order to preserve my own wellbeing if I'm going outside

#### Tasks
- [x] Create service that calls openaq.org API
- [x] Create state store (with actions, effects, & reducers) necessary to store AQ info on the client
- [x] Create component that displays AQ data in a popup
- [x] Update map component & container to show marks that, when clicked, display popup

#### Acceptance:
- [x] Deployed web app includes air quality data interface described in the tasks above

**Comment by Ricool06** [comment]
Chart is not currently styled, so look a bit ugly, but all the tasks have been completed here so this will be closed. PBIs will be added to remedy styling.
