### ISSUE TITLE
Add staging environment to CI/CD pipeline

### ISSUE THREAD

**Issue by Ricool06** [Ricool06/breathe#17]
As a: user
I want: to be sure that the service is not adversely affected by rolling continuous updates 
So that: I can access the app when I need it most

#### Tasks
- [ ] Edit travis pipeline to set environment variable that contains the "staging" or "production" string
- [ ] Edit the Terraform code to use this env var when deploying

#### Acceptance:
- [ ] Failed deployments to staging environment should stop the Travis pipeline
- [ ] Production stage should not be affected by staging deployment failure
