### ISSUE TITLE
SPIKE: Decide on best CI/CD system for project approach (copied from original repo)

### ISSUE THREAD

**Issue by Ricool06** [Ricool06/breathe#2]
This spike is to decide on the best CI/CD system that has support for the approach the developer of this project will take.
Given the problems that Travis CI showed in dealing with monorepos on the SOFT352 project, the following requirements must be met by the proposed tool:

* Free to use
* Has first-class support for monorepos OR there exists a fairly elegant remedy to the lack of support
* Must be pre-hosted, not managed by the developer outside of the pipeline file & minimal UI management
* Supports deployment to AWS

## Tasks
- [x] Create list of proposed CI/CD platforms
- [x] Create comparison matrix including above criteria for each
- [x] Try out each system and fill in matrix
- [x] Document chosen system on Github wiki/README of project

**Comment by Ricool06** [comment]
https://github.com/Ricool06/travis-monorepo

Sticking with Travis. After all that, there really isn't a better free CI system that has support for monorepos. Travis CI's support may not be first class, but it works, and is customizable enough that you can pretty much do most things.
Each project will have to have a .travis/build.sh or something to run all the needed build commands in one go. This setup is parallel so that's quite nice. :smile: 
Wiki has been updated: https://github.com/Ricool06/breathe/wiki/SPIKE:-Decide-on-best-CI-CD-system-for-project-approach
