### ISSUE TITLE
Style latest measurements chart

### ISSUE THREAD

**Issue by Ricool06** [Ricool06/breathe#27]
As a: User
I want: The latest measurements to be styled such that they are easily readable
So that: I can gather the information I need without fatigue or confusion

#### Tasks:
- [x] Colour each parameter uniformly
- [x] Sort each parameter
- [x] Make chart mobile-friendly and responsive

#### Acceptance:
- [x] Deployed web app contains the above features
