### ISSUE TITLE
Add historical data display for past 7 days (was 90)

### ISSUE THREAD

**Issue by Ricool06** [Ricool06/breathe#30]
As a: User
I want: To view the trend for air quality over the past 7 days
So that: I can make my own predictions about air quality, and have a reference point for determining if a given measurement is relatively low or high

#### Tasks
- [x] Add time series chart to data sheet
- [x] Create/refactor existing service for fetching historical data
- [x] Create/refactor existing state management to store historical data

#### Acceptance
- [x] Deployed app contains time series chart showing data for the past 7 days

**Comment by Ricool06** [comment]
This was 90 days, but this amount of data displayed all at once adversely affects performance. Another PBI will be added to allow the user to scroll back through time.
