### ISSUE TITLE
Display air quality index calculate with European EAQI method

### ISSUE THREAD

**Issue by Ricool06** [Ricool06/breathe#31]
#### Tasks
- [x] Create AQI calculation service
- [x] Create EAQI strategy
- [ ] ~~Add colour-coded AQI display to data sheet~~ (For readability, colour coding has been held back)

#### Acceptance
- [x] Tasks described above are completed and deployed to production

**Comment by Ricool06** [comment]
using EAQI instead as it is more up to date, simpler, and the recommended version: http://airindex.eea.europa.eu/#
