### ISSUE TITLE
Fix latest measurements display

### ISSUE THREAD

**Issue by Ricool06** [Ricool06/breathe#39]
As a: User
I want: the app to be robust to duplicate 'latest' data
So that: I can be sure the latest measurements on display are up to date.

#### Tasks
- [ ] ~~Filter non-latest measurements in latest-measurements service.~~
- [x] Filter non-latest measurements in latest-measurements effect.

#### Acceptance
- [x] Deployed app shows matching latest measurements on both historical chart and latest measurement chart.
