### ISSUE TITLE
Deploy 'hello world' app (copied from original repo)

### ISSUE THREAD

**Issue by Ricool06** [Ricool06/breathe#4]
# Requires: #1 #2 

As a: user
I want: the application to be deployed
So that: I can access the application

#### Tasks
- [x] Create Terraform project
- [x] Write Terraform code to manage remote tfstate
- [x] Write Terraform code to deploy web-ui project
- [x] Edit pipeline to deploy web-ui project after merging to master

Assumptions:
* Only a single environment for now: production

**Comment by Ricool06** [comment]
#14 is merged (as well as the numerous other PRs) and closes this. It would be nice if there was a tidier way to do this than shell scripts or bloating the .travis.yml but it is manageable for now.
Web-ui zip file is built and deployed directly, rather than using some sort of artefact store. This is to simplify the pipeline mostly.
Other notes:
* nvm.sh has to be sourced if the language isn't set to nodejs
