### ISSUE TITLE
Choose week from historical display

### ISSUE THREAD

**Issue by Ricool06** [Ricool06/breathe#40]
As a: User
I want: to be able to look at more than 1 week's past data
So that: I can observe air quality trends over a greater amount of time to give me more information

#### Tasks
- [x] Decide on slider vs datepicker approach
  - Slider approach to scroll back through weeks is decided
- [x] Create week slider component.
- [x] Hook up week slider component to data sheet

#### Acceptance
- [x] User is able to scroll through past weeks in deployed app
