### ISSUE TITLE
Create prediction API

### ISSUE THREAD

**Issue by Ricool06** [Ricool06/breathe#43]
As a: User
I want: to view a forecast of the next week's pollution
So that: I can prepare for low air quality

#### Tasks
- [ ] Read 90 days of historical data through S3
- [ ] Train model using data
- [ ] Use model to predict next week
- [ ] Shove it all in an API
- [ ] Write Terraform to deploy API

#### Acceptance
- [ ] Prediction API is deployed into live environment
